services:
  postgres:
    image: postgres:16-alpine
    container_name: flashsale-postgres
    restart: always
    environment:
      POSTGRES_DB: flashsale_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flashsale-net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: flashsale_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - flashsale-net

  redis:
    image: redis:7-alpine
    container_name: flashsale-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - flashsale-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: flashsale-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - flashsale-net

volumes:
  postgres_data:

networks:
  flashsale-net:
    driver: bridge