package com.ecommerce.flashsale_platform.modules.order.presentation;

import com.ecommerce.flashsale_platform.common.annotation.Idempotent;
import com.ecommerce.flashsale_platform.common.api.ApiResponse;
import com.ecommerce.flashsale_platform.modules.order.application.dto.request.PaymentRequest;
import com.ecommerce.flashsale_platform.modules.order.application.dto.response.PaymentResponse;
import com.ecommerce.flashsale_platform.modules.order.application.service.PaymentService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/orders")
@RequiredArgsConstructor
@Tag(name = "Payment", description = "Idempotent Financial Payment Simulation")
public class PaymentController {

    private final PaymentService paymentService;

    @PostMapping("/{orderNumber}/pay")
    @PreAuthorize("hasRole('CUSTOMER')")
    @Idempotent(expireSeconds = 600)
    @Operation(summary = "Pay an order with Idempotency-Key guarantee")
    public ResponseEntity<ApiResponse<PaymentResponse>> payOrder(
            @PathVariable String orderNumber,
            @Parameter(description = "Random unique UUID generated by frontend client", required = true)
            @RequestHeader("Idempotency-Key") String idempotencyKey,
            @Valid @RequestBody PaymentRequest request
            ) {
        PaymentResponse response = paymentService.payOrder(orderNumber, request);
        return ResponseEntity.ok(ApiResponse.ok("Payment processed successfully", response));
    }
}
